### ISSUE TITLE
Tried a test file myself with lzop basic exe file in Windows, de/compression lengths errors

### ISSUE THREAD

**Issue by mantissefr** [fengdh/minilzo-decompress.js#2]
I know it is quite hard to save a file from javascript to the client's hard disk so why compress ? Maybe to send to a server quicker, allright.

When a try with a substract of a big json file using lzop.exe with no option, it tells me that the compression lengths of Uint8Array is different from the decompression length of the Uint8Array.

I have a question by the way, is the size for compression or decompression of the Uint8array important ?

I am very interested by client side decompression as I am using angular js for the moment for a web dev app. Anyway, I think I am going to use a database, but using ajax to test API is really quicker then save all the data in a database first.

Anyway, I oculd not get your test file script to work with me test file (json raw and lzo versions) but I did not have the time to compile minilzo program for the moment, not to far to get it done though.

Would it be an issue because I am using lzop.exe main win32 binary and not minilzo binary ?

All the best.

**Comment by fengdh** [comment]
I'm not quite sure what you want to do, but I suggest you to take a look on a more robust and full-functioned lzo Javascript library: https://github.com/abraidwood/minilzo-js .

My minilzo-decompress.js is just a straight import from java-compress (https://code.google.com/p/java-compress/), but only part of decompression. With little understanding about LZO algorithm, I wrote it to decode compressed data for mdict file(.mdx/mdd) while abraidwood/minilzo-js was still buggy at that time. After communicating with the author, he had improved both quality and performance of minilzo-js since then.

**Comment by mantissefr** [comment]
Well, my questions were :
- Do compressed files differ using minilzo or lzop without going too in depths with comprssion options ?
- Is the Uint8Array length for compression or decompression important in your code ?

Anyway, I will have a look at the repository you are talking about.

Bye now.

**Comment by fengdh** [comment]
To be honest, I am not familiar with LZO manipulation, just having tried to decompress some data block compressed by other pe redople in a large dictionary file. Try to answer your questions, I have just searched on web.

1. I don't think you have to go into depth all options. With default settings lzop/minilzo can provide decent speed and compression rate for online process, except you have to manipulate some very large files or expect faster speed.

**Comment by fengdh** [comment]
To be honest, I'm not familiar with LZO rather than decompressing some data block compressed by other people in some quite large dictionary files. Try to answer your questions, I have just searched on web.
1. IMHO, it is not necessary to go into depth of any options. With default settings, lzop/minilzo can provide decent speed and balanced compression rate (for online usage). Maybe only for very large file (e.g. database archive), or pursuing a faster/est speed, you have to pickup some tricky options.
2. I still do not understanding your questions. How did you run lzop? I tried windows 32-bit version of lzop.exe with default settings to compress a 12M file and then decompress it back almost instantly. No error reported as you described in your initial post. According to Wikipedia page  on lzo, 

> - requires an additional buffer during compression (of size 8 kB or 64 kB, depending on compression level)
> - requires no additional memory for decompression other than the source and destination buffers

In my case to decompress data block from dictionary file, required buffer size is also stored with other information and can be decoded in advance.

To my understanding, lzop and minilzo works differenctly:
- lzop is a tool just like zip which is used to compress/decompress **a collection of files**, storing directory structure and other meta information together. Each file is compressed as a lzo raw data block.
- minilzo is a library which is used to process a data block into a lzo compressed **raw data block** or back with no additional information. You have to store information such as required buffer size in you own way, and retrieve it later.
